name: test
services:
  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./db:/data/db
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  # https://hub.docker.com/_/mongo-express
  # https://github.com/mongo-express/mongo-express
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://admin:1234@mongo:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_OPTIONS_READONLY: true

  # https://hub.docker.com/_/node
  node:
    build: .
    container_name: node
    restart: always
    # ports:
    #   - 3000:3000
    depends_on:
      - mongo
      - mongo-express

  # https://hub.docker.com/_/nginx
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
      - 8081:8081
      - 27017:27017
    depends_on:
      - node
