FROM node:22-alpine
WORKDIR /app
RUN apk add --no-cache \
    git \
    && git clone --depth 1 https://shinich39:<ACCESS_TOEKN>@github.com/shinich39/docker-node-example.git . \
    && npm ci
CMD ["node", "bin/app.js"]
EXPOSE 3000

# prevent cache for repository updates
# docker-compose build --no-cache && docker-compose up -d