FROM node:22-slim
WORKDIR /app
RUN apt-get update || : && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    build-essential
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
CMD ["node", "bin/app.js"]
EXPOSE 3000